### PR TITLE
Updates to docs, environments, and bug fixes

### PR DESCRIPTION
**Pull request by Rohan138**
Changes:
- Added conda_uint8_patch.sh
- Added example scripts for training with Stable-Baselines3: run_scripts/sb3_train.py and run_scripts/sb3_independent.py
- Refactored setup.py and updated requirements
- Added the inequity_averse_rewards, alpha, beta arguments
- Fixed pettingzoo wrapper and removed add_default_args from the environments themselves
- Other misc fixes

Note: I'll be creating two more PRs in the near future (moved outside this PR for clarity) to:
- Update to the latest RLlib version and (hopefully) make it so that we can remove both patch scripts and release the environments as a pip package
- Switch MapEnv from RLlib's MultiAgentEnv to a PettingZoo ParallelEnv with an RLlib wrapper; this'll enable better integration with e.g. SB3, Tianshou and so on, while being fully backwards compatible

### CODE REVIEW

**Comment by eugenevinitsky** [comment]
Let me know when this is ready for review?

**Comment by Rohan138** [comment]
This one's ready for review; all three PRs are self-contained, although updating the RLlib version is difficult because of how many changes there are.

**Comment by eugenevinitsky** [comment]
Yeah, that RLlib code is going to be incredibly hard to update given how much they have changed their API. Okay, I'll review this at some point during the holidays. Thanks for the PR!

**Comment by jkterry1** [comment]
@eugenevinitsky it's been a month, so I'm just following up on this :)

**Review by eugenevinitsky — APPROVED** [review]

**Comment by eugenevinitsky** [comment]
Approved! Thanks for this.

**Pull request merged**
